FROM maven:3.8.4-openjdk-17-slim AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package
 
FROM openjdk:17-slim
WORKDIR /app
COPY --from=build /app/target/medilink.war /app/medilink.war
EXPOSE 8080
CMD ["java", "-jar", "medilink.war"] 