name: Medilink CI/CD Pipeline

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  backend:
    name: Backend Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and Test Backend
        run: |
          cd src
          mvn clean package

      - name: Upload Backend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-artifact
          path: src/target/*.war

  frontend:
    name: Frontend Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: medi_front/package-lock.json

      - name: Install Frontend Dependencies
        run: |
          cd medi_front
          npm ci

      - name: Build Frontend
        run: |
          cd medi_front
          npm run build

      - name: Upload Frontend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-artifact
          path: medi_front/dist

  android:
    name: Android Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build Android App
        run: |
          cd medi_mobile
          ./gradlew assembleDebug

      - name: Upload Android Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-artifact
          path: medi_mobile/app/build/outputs/apk/debug/*.apk

  deploy:
    name: Deploy
    needs: [backend, frontend, android]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to AWS
        run: |
          # Deploy backend to ECS/EC2
          aws ecs update-service --cluster medilink-cluster --service backend-service --force-new-deployment
          
          # Deploy frontend to S3
          aws s3 sync artifacts/frontend-artifact s3://${{ secrets.S3_BUCKET }} --delete
          
          # Upload Android APK to S3
          aws s3 cp artifacts/android-artifact/*.apk s3://${{ secrets.ANDROID_BUCKET }}/latest.apk 